[[constraint]]
  name = "code.cloudfoundry.org/go-loggregator"
  version = "6.0.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"
